version: '4.17.0'
services:
  voicevox:
    container_name: voicevox
    hostname: voicevox
    build:
      context: voicevox
    networks:
      - waifuvoice_net
    ports:
      - 50020:50021
  whisper:
    container_name: whisper
    hostname: whisper
    build:
      context: whisper
    networks:
      - waifuvoice_net
    ports:
      - 9000:9000
    environment:
      - ASR_MODEL=small
  libretranslate:
    container_name: libretranslate
    hostname: libretranslate
    build:
      context: libretranslate
    networks:
      - waifuvoice_net
    ports:
      - 5000:5000
networks:
  waifuvoice_net:
    name: waifuvoice_net